server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cards
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

