server:
  servlet:
    context-path: /api

spring:
  datasource:
    #TODO utiliser postgres
    url: jdbc:h2:mem:cards
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
